apiVersion: validation.spectrocloud.labs/v1alpha1
kind: AwsValidator
metadata:
  name: awsvalidator-spectro-cloud-minimal-dynamic
spec:
  auth:
    secretName: aws-creds
  defaultRegion: us-west-1
  iamRoleRules:
  - iamPolicies:
    - name: Minimal Policy - Dynamic Provisioning
      statements:
      - actions:
        - "autoscaling:StartInstanceRefresh"
        - "cloudformation:CreateStack"
        - "cloudformation:DescribeStacks"
        - "cloudformation:UpdateStack"
        - "ec2:AllocateAddress"
        - "ec2:AssociateAddress"
        - "ec2:AssociateRouteTable"
        - "ec2:AttachInternetGateway"
        - "ec2:AuthorizeSecurityGroupIngress"
        - "ec2:CreateInternetGateway"
        - "ec2:CreateNatGateway"
        - "ec2:CreateRoute"
        - "ec2:CreateRouteTable"
        - "ec2:CreateSecurityGroup"
        - "ec2:CreateSubnet"
        - "ec2:CreateTags"
        - "ec2:CreateVpc"
        - "ec2:DeleteInternetGateway"
        - "ec2:DeleteNatGateway"
        - "ec2:DeleteNetworkInterface"
        - "ec2:DeleteRoute"
        - "ec2:DeleteRouteTable"
        - "ec2:DeleteSecurityGroup"
        - "ec2:DeleteSubnet"
        - "ec2:DeleteTags"
        - "ec2:DeleteVpc"
        - "ec2:DescribeAddresses"
        - "ec2:DescribeAvailabilityZones"
        - "ec2:DescribeDhcpOptions"
        - "ec2:DescribeImages"
        - "ec2:DescribeInstances"
        - "ec2:DescribeInternetGateways"
        - "ec2:DescribeIpamPools"
        - "ec2:DescribeIpv6Pools"
        - "ec2:DescribeKeyPairs"
        - "ec2:DescribeNatGateways"
        - "ec2:DescribeNetworkAcls"
        - "ec2:DescribeNetworkInterfaceAttribute"
        - "ec2:DescribeNetworkInterfaces"
        - "ec2:DescribeRegions"
        - "ec2:DescribeRouteTables"
        - "ec2:DescribeSecurityGroups"
        - "ec2:DescribeSubnets"
        - "ec2:DescribeTags"
        - "ec2:DescribeVolumes"
        - "ec2:DescribeVpcAttribute"
        - "ec2:DescribeVpcs"
        - "ec2:DetachInternetGateway"
        - "ec2:DisassociateAddress"
        - "ec2:DisassociateRouteTable"
        - "ec2:ModifyInstanceAttribute"
        - "ec2:ModifyNetworkInterfaceAttribute"
        - "ec2:ModifySubnetAttribute"
        - "ec2:ModifyVpcAttribute"
        - "ec2:ReleaseAddress"
        - "ec2:ReplaceRoute"
        - "ec2:RevokeSecurityGroupIngress"
        - "ec2:RunInstances"
        - "ec2:TerminateInstances"
        - "ecr:BatchCheckLayerAvailability"
        - "ecr:BatchGetImage"
        - "ecr:DescribeRepositories"
        - "ecr:GetAuthorizationToken"
        - "ecr:GetDownloadUrlForLayer"
        - "ecr:GetRepositoryPolicy"
        - "ecr:ListImages"
        - "eks:DescribeCluster"
        - "eks:ListClusters"
        - "elasticloadbalancing:ConfigureHealthCheck"
        - "elasticloadbalancing:CreateLoadBalancer"
        - "elasticloadbalancing:DeleteLoadBalancer"
        - "elasticloadbalancing:DeregisterInstancesFromLoadBalancer"
        - "elasticloadbalancing:DescribeLoadBalancerAttributes"
        - "elasticloadbalancing:DescribeLoadBalancers"
        - "elasticloadbalancing:DescribeTags"
        - "elasticloadbalancing:DescribeTargetHealth"
        - "elasticloadbalancing:ModifyLoadBalancerAttributes"
        - "elasticloadbalancing:RegisterInstancesWithLoadBalancer"
        - "iam:AddRoleToInstanceProfile"
        - "iam:CreateInstanceProfile"
        - "iam:DeleteInstanceProfile"
        - "iam:GetInstanceProfile"
        - "iam:PassRole"
        - "iam:RemoveRoleFromInstanceProfile"
        - "pricing:GetProducts"
        - "secretsmanager:CreateSecret"
        - "secretsmanager:DeleteSecret"
        - "secretsmanager:GetSecretValue"
        - "secretsmanager:TagResource"
        - "ssm:UpdateInstanceInformation"
        - "ssmmessages:CreateControlChannel"
        - "ssmmessages:CreateDataChannel"
        - "ssmmessages:OpenControlChannel"
        - "ssmmessages:OpenDataChannel"
        - "sts:AssumeRole"
        - "tag:GetResources"
        effect: Allow
        resources:
        - "*"
      - actions:
        - "iam:PassRole"
        effect: Allow
        resources:
        - "arn:*:iam::*:role/*.cluster-api-provider-aws.sigs.k8s.io"
      version: "2012-10-17"
    iamRoleName: SpectroCloudRole