apiVersion: validation.spectrocloud.labs/v1alpha1
kind: AwsValidator
metadata:
  name: awsvalidator-spectro-cloud-minimal-static
spec:
  auth:
    secretName: aws-creds
  defaultRegion: us-west-1
  iamRoleRules:
  - iamPolicies:
    - name: Minimal Policy - Static Provisioning
      statements:
      - actions:
        - "autoscaling:StartInstanceRefresh"
        - "cloudformation:CreateStack"
        - "cloudformation:DescribeStacks"
        - "cloudformation:UpdateStack"
        - "ec2:AllocateAddress"
        - "ec2:AssociateAddress"
        - "ec2:AttachVolume"
        - "ec2:AuthorizeSecurityGroupIngress"
        - "ec2:CreateSecurityGroup"
        - "ec2:CreateTags"
        - "ec2:DeleteNetworkInterface"
        - "ec2:DeleteSecurityGroup"
        - "ec2:DescribeAddresses"
        - "ec2:DescribeAvailabilityZones"
        - "ec2:DescribeImages"
        - "ec2:DescribeInstances"
        - "ec2:DescribeKeyPairs"
        - "ec2:DescribeNatGateways"
        - "ec2:DescribeNetworkInterfaceAttribute"
        - "ec2:DescribeNetworkInterfaces"
        - "ec2:DescribeRegions"
        - "ec2:DescribeRouteTables"
        - "ec2:DescribeSecurityGroups"
        - "ec2:DescribeSubnets"
        - "ec2:DescribeVolumes"
        - "ec2:DescribeVolumesModifications"
        - "ec2:DescribeVpcAttribute"
        - "ec2:DescribeVpcs"
        - "ec2:DetachInternetGateway"
        - "ec2:DetachVolume"
        - "ec2:DisassociateAddress"
        - "ec2:ModifyInstanceAttribute"
        - "ec2:ModifyNetworkInterfaceAttribute"
        - "ec2:ModifyVolume"
        - "ec2:ModifyVpcAttribute"
        - "ec2:ReleaseAddress"
        - "ec2:RevokeSecurityGroupIngress"
        - "ec2:RunInstances"
        - "ec2:TerminateInstances"
        - "eks:DescribeCluster"
        - "eks:ListClusters"
        - "elasticloadbalancing:ConfigureHealthCheck"
        - "elasticloadbalancing:CreateLoadBalancer"
        - "elasticloadbalancing:DeleteLoadBalancer"
        - "elasticloadbalancing:DeregisterInstancesFromLoadBalancer"
        - "elasticloadbalancing:DescribeLoadBalancerAttributes"
        - "elasticloadbalancing:DescribeLoadBalancers"
        - "elasticloadbalancing:DescribeTags"
        - "elasticloadbalancing:DescribeTargetHealth"
        - "elasticloadbalancing:DetachLoadBalancerFromSubnets"
        - "elasticloadbalancing:ModifyLoadBalancerAttributes"
        - "elasticloadbalancing:RegisterInstancesWithLoadBalancer"
        - "iam:AddRoleToInstanceProfile"
        - "iam:CreateInstanceProfile"
        - "iam:DeleteInstanceProfile"
        - "iam:GetInstanceProfile"
        - "iam:RemoveRoleFromInstanceProfile"
        - "pricing:GetProducts"
        - "s3:GetEncryptionConfiguration"
        - "secretsmanager:CreateSecret"
        - "secretsmanager:DeleteSecret"
        - "secretsmanager:GetSecretValue"
        - "secretsmanager:TagResource"
        - "ssm:UpdateInstanceInformation"
        - "ssmmessages:CreateControlChannel"
        - "ssmmessages:CreateDataChannel"
        - "ssmmessages:OpenControlChannel"
        - "ssmmessages:OpenDataChannel"
        - "sts:AssumeRole"
        - "tag:GetResources"
        effect: Allow
        resources:
        - "*"
      - actions:
        - "iam:PassRole"
        effect: Allow
        resources:
        - "arn:*:iam::*:role/*.cluster-api-provider-aws.sigs.k8s.io"
      version: "2012-10-17"
    iamRoleName: SpectroCloudRole