apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.12.0
  name: awsvalidators.validation.spectrocloud.labs
spec:
  group: validation.spectrocloud.labs
  names:
    kind: AwsValidator
    listKind: AwsValidatorList
    plural: awsvalidators
    singular: awsvalidator
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: AwsValidator is the Schema for the awsvalidators API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: AwsValidatorSpec defines the desired state of AwsValidator
            properties:
              auth:
                properties:
                  secretName:
                    description: 'Option 1: lookup AWS creds from a secret'
                    type: string
                  serviceAccountName:
                    description: 'Option 2: specify a service account (EKS)'
                    type: string
                type: object
              defaultRegion:
                type: string
              iamGroupRules:
                items:
                  properties:
                    iamGroupName:
                      type: string
                    iamPolicies:
                      items:
                        properties:
                          name:
                            type: string
                          statements:
                            items:
                              properties:
                                actions:
                                  items:
                                    type: string
                                  type: array
                                condition:
                                  properties:
                                    key:
                                      type: string
                                    type:
                                      type: string
                                    values:
                                      items:
                                        type: string
                                      type: array
                                  required:
                                  - key
                                  - type
                                  - values
                                  type: object
                                effect:
                                  type: string
                                resources:
                                  items:
                                    type: string
                                  type: array
                              required:
                              - actions
                              - effect
                              - resources
                              type: object
                            type: array
                          version:
                            type: string
                        required:
                        - name
                        - statements
                        - version
                        type: object
                      type: array
                  required:
                  - iamGroupName
                  - iamPolicies
                  type: object
                type: array
              iamPolicyRules:
                items:
                  properties:
                    iamPolicies:
                      items:
                        properties:
                          name:
                            type: string
                          statements:
                            items:
                              properties:
                                actions:
                                  items:
                                    type: string
                                  type: array
                                condition:
                                  properties:
                                    key:
                                      type: string
                                    type:
                                      type: string
                                    values:
                                      items:
                                        type: string
                                      type: array
                                  required:
                                  - key
                                  - type
                                  - values
                                  type: object
                                effect:
                                  type: string
                                resources:
                                  items:
                                    type: string
                                  type: array
                              required:
                              - actions
                              - effect
                              - resources
                              type: object
                            type: array
                          version:
                            type: string
                        required:
                        - name
                        - statements
                        - version
                        type: object
                      type: array
                    iamPolicyArn:
                      type: string
                  required:
                  - iamPolicies
                  - iamPolicyArn
                  type: object
                type: array
              iamRoleRules:
                items:
                  properties:
                    iamPolicies:
                      items:
                        properties:
                          name:
                            type: string
                          statements:
                            items:
                              properties:
                                actions:
                                  items:
                                    type: string
                                  type: array
                                condition:
                                  properties:
                                    key:
                                      type: string
                                    type:
                                      type: string
                                    values:
                                      items:
                                        type: string
                                      type: array
                                  required:
                                  - key
                                  - type
                                  - values
                                  type: object
                                effect:
                                  type: string
                                resources:
                                  items:
                                    type: string
                                  type: array
                              required:
                              - actions
                              - effect
                              - resources
                              type: object
                            type: array
                          version:
                            type: string
                        required:
                        - name
                        - statements
                        - version
                        type: object
                      type: array
                    iamRoleName:
                      type: string
                  required:
                  - iamPolicies
                  - iamRoleName
                  type: object
                type: array
              iamUserRules:
                items:
                  properties:
                    iamPolicies:
                      items:
                        properties:
                          name:
                            type: string
                          statements:
                            items:
                              properties:
                                actions:
                                  items:
                                    type: string
                                  type: array
                                condition:
                                  properties:
                                    key:
                                      type: string
                                    type:
                                      type: string
                                    values:
                                      items:
                                        type: string
                                      type: array
                                  required:
                                  - key
                                  - type
                                  - values
                                  type: object
                                effect:
                                  type: string
                                resources:
                                  items:
                                    type: string
                                  type: array
                              required:
                              - actions
                              - effect
                              - resources
                              type: object
                            type: array
                          version:
                            type: string
                        required:
                        - name
                        - statements
                        - version
                        type: object
                      type: array
                    iamUserName:
                      type: string
                  required:
                  - iamPolicies
                  - iamUserName
                  type: object
                type: array
              serviceQuotaRules:
                items:
                  properties:
                    region:
                      type: string
                    serviceCode:
                      type: string
                    serviceQuotas:
                      items:
                        properties:
                          buffer:
                            type: integer
                          name:
                            type: string
                        required:
                        - buffer
                        - name
                        type: object
                      type: array
                  required:
                  - region
                  - serviceCode
                  - serviceQuotas
                  type: object
                type: array
              tagRules:
                items:
                  properties:
                    arns:
                      items:
                        type: string
                      type: array
                    expectedValue:
                      type: string
                    key:
                      type: string
                    region:
                      type: string
                    resourceType:
                      type: string
                  required:
                  - arns
                  - expectedValue
                  - key
                  - region
                  - resourceType
                  type: object
                type: array
            required:
            - auth
            - defaultRegion
            type: object
          status:
            description: AwsValidatorStatus defines the observed state of AwsValidator
            properties:
              conditions:
                items:
                  properties:
                    details:
                      description: Human-readable messages indicating additional details
                        for the last transition.
                      items:
                        type: string
                      type: array
                    failures:
                      description: Human-readable messages indicating additional failure
                        details for the last transition.
                      items:
                        type: string
                      type: array
                    lastValidationTime:
                      description: Timestamp of most recent execution of the validation
                        rule associated with the condition.
                      format: date-time
                      type: string
                    message:
                      description: Human-readable message indicating details about
                        the last transition.
                      type: string
                    status:
                      description: True if the validation rule succeeded, otherwise
                        False
                      type: string
                    validationRule:
                      description: Unique, one-word description of the validation
                        rule associated with the condition.
                      type: string
                    validationType:
                      description: Unique, one-word description of the validation
                        type associated with the condition.
                      type: string
                  required:
                  - lastValidationTime
                  - status
                  - validationRule
                  - validationType
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
