apiVersion: v2
name: validator-plugin-oci
description: >-
  Perform various OCI validations (registry authentication, downloading
  artifacts, etc.)
type: application
version: 0.0.10
appVersion: 0.0.2
